export type WorkforceSectionType =
  | "LEADERSHIP"
  | "QUALITY_CONTROL"
  | "PRODUCTION"
  | "PACKAGING"
  | "CLEANING"
  | "SUPPORT"

export type WorkforceEmployee = {
  id: string
  name: string
  role: string
  station: string
  section: WorkforceSectionType
  shift: "MORNING" | "EVENING" | "FULL_DAY"
  status: "ACTIVE" | "BREAK" | "OFFLINE"
}

export type WorkforceCapacity = {
  minimumOperators: number
  optimalOperators: number
  maximumOperators: number
}

export type WorkforceStation = {
  id: string
  name: string
  section: WorkforceSectionType
  lead?: string
  color: string
  dailyCapacity: number
  capacity: WorkforceCapacity
  employees: WorkforceEmployee[]
}

export const CENTRAL_KITCHEN_WORKFORCE: WorkforceStation[] = [
  {
    id: "ST-LEAD",
    name: "Executive Leadership",
    section: "LEADERSHIP",
    lead: "Culinary Operations Director",
    color: "#FFFFFF",
    dailyCapacity: 0,
    capacity: {
      minimumOperators: 1,
      optimalOperators: 2,
      maximumOperators: 3,
    },
    employees: [
      {
        id: "POS-001",
        name: "Culinary Operations Director",
        role: "Executive Leadership",
        station: "Executive Leadership",
        section: "LEADERSHIP",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
      {
        id: "POS-002",
        name: "Food Safety Officer",
        role: "Food Safety",
        station: "Food Safety",
        section: "QUALITY_CONTROL",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
    ],
  },
  {
    id: "ST-PREPARATION",
    name: "Preparation Team",
    section: "SUPPORT",
    lead: "Preparation Team Lead",
    color: "#38BDF8",
    dailyCapacity: 500,
    capacity: {
      minimumOperators: 3,
      optimalOperators: 5,
      maximumOperators: 7,
    },
    employees: [
      {
        id: "POS-010",
        name: "Preparation Team Lead",
        role: "Preparation Lead",
        station: "Preparation Team",
        section: "SUPPORT",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
      {
        id: "POS-011",
        name: "Vegetable Preparation Position",
        role: "Vegetable Preparation",
        station: "Preparation Team",
        section: "SUPPORT",
        shift: "MORNING",
        status: "ACTIVE",
      },
      {
        id: "POS-012",
        name: "Butchery Position",
        role: "Butchery",
        station: "Preparation Team",
        section: "SUPPORT",
        shift: "MORNING",
        status: "ACTIVE",
      },
      {
        id: "POS-013",
        name: "Preparation Position 1",
        role: "Preparation Team",
        station: "Preparation Team",
        section: "SUPPORT",
        shift: "MORNING",
        status: "ACTIVE",
      },
      {
        id: "POS-014",
        name: "Preparation Position 2",
        role: "Preparation Team",
        station: "Preparation Team",
        section: "SUPPORT",
        shift: "MORNING",
        status: "ACTIVE",
      },
    ],
  },
  {
    id: "ST-BREAKFAST",
    name: "Breakfast Team",
    section: "PRODUCTION",
    lead: "Breakfast Team Lead",
    color: "#0EA5E9",
    dailyCapacity: 400,
    capacity: {
      minimumOperators: 2,
      optimalOperators: 3,
      maximumOperators: 5,
    },
    employees: [
      {
        id: "POS-020",
        name: "Breakfast Team Lead",
        role: "Breakfast Lead",
        station: "Breakfast Team",
        section: "PRODUCTION",
        shift: "MORNING",
        status: "ACTIVE",
      },
      {
        id: "POS-021",
        name: "Breakfast Cook Position 1",
        role: "Breakfast Cook",
        station: "Breakfast Team",
        section: "PRODUCTION",
        shift: "MORNING",
        status: "ACTIVE",
      },
      {
        id: "POS-022",
        name: "Breakfast Cook Position 2",
        role: "Breakfast Cook",
        station: "Breakfast Team",
        section: "PRODUCTION",
        shift: "MORNING",
        status: "ACTIVE",
      },
    ],
  },
  {
    id: "ST-HOT-KITCHEN",
    name: "Lunch & Dinner Team",
    section: "PRODUCTION",
    lead: "Hot Kitchen Team Lead",
    color: "#CCFF33",
    dailyCapacity: 1200,
    capacity: {
      minimumOperators: 4,
      optimalOperators: 6,
      maximumOperators: 9,
    },
    employees: [
      {
        id: "POS-030",
        name: "Hot Kitchen Team Lead",
        role: "Hot Kitchen Lead",
        station: "Lunch & Dinner Team",
        section: "PRODUCTION",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
      {
        id: "POS-031",
        name: "Hot Kitchen Cook Position 1",
        role: "Hot Kitchen Cook",
        station: "Lunch & Dinner Team",
        section: "PRODUCTION",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
      {
        id: "POS-032",
        name: "Hot Kitchen Cook Position 2",
        role: "Hot Kitchen Cook",
        station: "Lunch & Dinner Team",
        section: "PRODUCTION",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
      {
        id: "POS-033",
        name: "Hot Kitchen Cook Position 3",
        role: "Hot Kitchen Cook",
        station: "Lunch & Dinner Team",
        section: "PRODUCTION",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
    ],
  },
  {
    id: "ST-COLD-SECTION",
    name: "Cold Section Team",
    section: "PRODUCTION",
    lead: "Cold Section Lead",
    color: "#22D3EE",
    dailyCapacity: 500,
    capacity: {
      minimumOperators: 2,
      optimalOperators: 4,
      maximumOperators: 6,
    },
    employees: [
      {
        id: "POS-040",
        name: "Cold Section Lead",
        role: "Cold Kitchen Lead",
        station: "Cold Section Team",
        section: "PRODUCTION",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
      {
        id: "POS-041",
        name: "Cold Section Cook Position 1",
        role: "Cold Section Cook",
        station: "Cold Section Team",
        section: "PRODUCTION",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
      {
        id: "POS-042",
        name: "Cold Section Cook Position 2",
        role: "Cold Section Cook",
        station: "Cold Section Team",
        section: "PRODUCTION",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
      {
        id: "POS-043",
        name: "Cold Section Cook Position 3",
        role: "Cold Section Cook",
        station: "Cold Section Team",
        section: "PRODUCTION",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
    ],
  },
  {
    id: "ST-SALADS",
    name: "Salads Team",
    section: "PRODUCTION",
    lead: "Salads Team Lead",
    color: "#22C55E",
    dailyCapacity: 500,
    capacity: {
      minimumOperators: 2,
      optimalOperators: 4,
      maximumOperators: 6,
    },
    employees: [
      {
        id: "POS-050",
        name: "Salads Team Lead",
        role: "Salads Lead",
        station: "Salads Team",
        section: "PRODUCTION",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
      {
        id: "POS-051",
        name: "Salad Production Position 1",
        role: "Salads Production",
        station: "Salads Team",
        section: "PRODUCTION",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
      {
        id: "POS-052",
        name: "Salad Production Position 2",
        role: "Salads Production",
        station: "Salads Team",
        section: "PRODUCTION",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
      {
        id: "POS-053",
        name: "Salad Production Position 3",
        role: "Salads Production",
        station: "Salads Team",
        section: "PRODUCTION",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
    ],
  },
  {
    id: "ST-BAKERY",
    name: "Bakery Team",
    section: "PRODUCTION",
    lead: "Bakery Team Lead",
    color: "#FB923C",
    dailyCapacity: 300,
    capacity: {
      minimumOperators: 1,
      optimalOperators: 2,
      maximumOperators: 4,
    },
    employees: [
      {
        id: "POS-060",
        name: "Bakery Team Lead",
        role: "Bakery Lead",
        station: "Bakery Team",
        section: "PRODUCTION",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
      {
        id: "POS-061",
        name: "Bread Maker Position",
        role: "Bread Production",
        station: "Bakery Team",
        section: "PRODUCTION",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
    ],
  },
  {
    id: "ST-PASTRY",
    name: "Pastry Section",
    section: "PRODUCTION",
    lead: "Pastry Chef Lead",
    color: "#F472B6",
    dailyCapacity: 300,
    capacity: {
      minimumOperators: 1,
      optimalOperators: 3,
      maximumOperators: 5,
    },
    employees: [
      {
        id: "POS-065",
        name: "Pastry Chef Lead",
        role: "Pastry Lead",
        station: "Pastry Section",
        section: "PRODUCTION",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
      {
        id: "POS-066",
        name: "Pastry Production Position 1",
        role: "Pastry Production",
        station: "Pastry Section",
        section: "PRODUCTION",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
      {
        id: "POS-067",
        name: "Pastry Production Position 2",
        role: "Pastry Production",
        station: "Pastry Section",
        section: "PRODUCTION",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
    ],
  },
  {
    id: "ST-PACKAGING",
    name: "Packaging Team",
    section: "PACKAGING",
    lead: "Packaging Team Lead",
    color: "#FB7185",
    dailyCapacity: 1500,
    capacity: {
      minimumOperators: 6,
      optimalOperators: 10,
      maximumOperators: 14,
    },
    employees: [
      {
        id: "POS-070",
        name: "Packaging Team Lead",
        role: "Packaging Lead",
        station: "Packaging Team",
        section: "PACKAGING",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
      {
        id: "POS-071",
        name: "Packaging Operator Position 1",
        role: "Packaging Operator",
        station: "Packaging Team",
        section: "PACKAGING",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
      {
        id: "POS-072",
        name: "Packaging Operator Position 2",
        role: "Packaging Operator",
        station: "Packaging Team",
        section: "PACKAGING",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
      {
        id: "POS-073",
        name: "Packaging Operator Position 3",
        role: "Packaging Operator",
        station: "Packaging Team",
        section: "PACKAGING",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
      {
        id: "POS-074",
        name: "Packaging Operator Position 4",
        role: "Packaging Operator",
        station: "Packaging Team",
        section: "PACKAGING",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
      {
        id: "POS-075",
        name: "Packaging Operator Position 5",
        role: "Packaging Operator",
        station: "Packaging Team",
        section: "PACKAGING",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
      {
        id: "POS-076",
        name: "Packaging Operator Position 6",
        role: "Packaging Operator",
        station: "Packaging Team",
        section: "PACKAGING",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
      {
        id: "POS-077",
        name: "Packaging Operator Position 7",
        role: "Packaging Operator",
        station: "Packaging Team",
        section: "PACKAGING",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
      {
        id: "POS-078",
        name: "Packaging Operator Position 8",
        role: "Packaging Operator",
        station: "Packaging Team",
        section: "PACKAGING",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
      {
        id: "POS-079",
        name: "Packaging Operator Position 9",
        role: "Packaging Operator",
        station: "Packaging Team",
        section: "PACKAGING",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
      {
        id: "POS-080",
        name: "Packaging Operator Position 10",
        role: "Packaging Operator",
        station: "Packaging Team",
        section: "PACKAGING",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
    ],
  },
  {
    id: "ST-CLEANING",
    name: "Cleaning Team",
    section: "CLEANING",
    lead: "Cleaning Team Lead",
    color: "#F97316",
    dailyCapacity: 0,
    capacity: {
      minimumOperators: 4,
      optimalOperators: 7,
      maximumOperators: 10,
    },
    employees: [
      {
        id: "POS-090",
        name: "Cleaning Team Lead",
        role: "Cleaning Lead",
        station: "Cleaning Team",
        section: "CLEANING",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
      {
        id: "POS-091",
        name: "Cleaning Operator Position 1",
        role: "Cleaning Operator",
        station: "Cleaning Team",
        section: "CLEANING",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
      {
        id: "POS-092",
        name: "Cleaning Operator Position 2",
        role: "Cleaning Operator",
        station: "Cleaning Team",
        section: "CLEANING",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
      {
        id: "POS-093",
        name: "Cleaning Operator Position 3",
        role: "Cleaning Operator",
        station: "Cleaning Team",
        section: "CLEANING",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
      {
        id: "POS-094",
        name: "Cleaning Operator Position 4",
        role: "Cleaning Operator",
        station: "Cleaning Team",
        section: "CLEANING",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
      {
        id: "POS-095",
        name: "Cleaning Operator Position 5",
        role: "Cleaning Operator",
        station: "Cleaning Team",
        section: "CLEANING",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
      {
        id: "POS-096",
        name: "Cleaning Operator Position 6",
        role: "Cleaning Operator",
        station: "Cleaning Team",
        section: "CLEANING",
        shift: "FULL_DAY",
        status: "ACTIVE",
      },
    ],
  },
]